/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'auth-users': AuthUserAuthOperations;
  };
  blocks: {};
  collections: {
    'auth-users': AuthUser;
    'demo-pages': DemoPage;
    activities: Activity;
    announcements: Announcement;
    'association-pages': AssociationPage;
    'gallery-works': GalleryWork;
    news: News;
    'media-assets': MediaAsset;
    'recruitment-cycles': RecruitmentCycle;
    'form-definitions': FormDefinition;
    'form-versions': FormVersion;
    'membership-applications': MembershipApplication;
    members: Member;
    'review-actions': ReviewAction;
    'account-claims': AccountClaim;
    'member-intake-applications': MemberIntakeApplication;
    'audit-events': AuditEvent;
    'permission-overrides': PermissionOverride;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'auth-users': AuthUsersSelect<false> | AuthUsersSelect<true>;
    'demo-pages': DemoPagesSelect<false> | DemoPagesSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    'association-pages': AssociationPagesSelect<false> | AssociationPagesSelect<true>;
    'gallery-works': GalleryWorksSelect<false> | GalleryWorksSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'media-assets': MediaAssetsSelect<false> | MediaAssetsSelect<true>;
    'recruitment-cycles': RecruitmentCyclesSelect<false> | RecruitmentCyclesSelect<true>;
    'form-definitions': FormDefinitionsSelect<false> | FormDefinitionsSelect<true>;
    'form-versions': FormVersionsSelect<false> | FormVersionsSelect<true>;
    'membership-applications': MembershipApplicationsSelect<false> | MembershipApplicationsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'review-actions': ReviewActionsSelect<false> | ReviewActionsSelect<true>;
    'account-claims': AccountClaimsSelect<false> | AccountClaimsSelect<true>;
    'member-intake-applications': MemberIntakeApplicationsSelect<false> | MemberIntakeApplicationsSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    'permission-overrides': PermissionOverridesSelect<false> | PermissionOverridesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: AuthUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AuthUserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-users".
 */
export interface AuthUser {
  id: string;
  displayName: string;
  accountType: 'student' | 'external';
  studentNumber?: string | null;
  status: 'pendingActivation' | 'pendingClaim' | 'pendingApproval' | 'claimBlocked' | 'active' | 'disabled';
  role: 'member' | 'staff' | 'cadre' | 'admin' | 'owner';
  defaultRoleExpiresAt?: string | null;
  temporaryCredentialExpiresAt?: string | null;
  recordVersion: number;
  /**
   * Ordinary staff access normally expires after 10 months.
   */
  accessExpiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'auth-users';
}
/**
 * 仅供演示和工程调试，不是正式会员身份核验或账号申领入口；不得录入真实个人资料。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demo-pages".
 */
export interface DemoPage {
  id: string;
  title: string;
  slug: string;
  summary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 活动发布后出现在公开活动目录及详情页。先保存草稿并核对介绍，再使用现有发布动作公开；取消会保留公开说明，Unpublish 才会移除。点击列表标题进入编辑。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: string;
  activityType: 'temporary' | 'standing';
  /**
   * 显示在公开活动目录和活动详情页顶部。
   */
  title: string;
  /**
   * 可公开，供活动目录快速了解内容；不代替活动介绍。
   */
  summary?: string | null;
  /**
   * 创建时由服务端生成，后续不可修改。
   */
  slug: string;
  /**
   * 只填写纯文本地点，不填写地图或链接。
   */
  location?: string | null;
  /**
   * 临时活动发布时必填。
   */
  startsAt?: string | null;
  /**
   * 临时活动发布时必填，且必须晚于开始时间。
   */
  endsAt?: string | null;
  /**
   * 常驻活动发布时必填，例如“每周五 19:30–21:00”。
   */
  scheduleText?: string | null;
  /**
   * 取消后活动仍公开；如需移除请使用 Unpublish 下线。
   */
  isCancelled: boolean;
  /**
   * 取消版本发布时必填，将向访客公开。
   */
  cancellationNote?: string | null;
  /**
   * 活动详情页公开展示的主要内容。
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  historySortAt?: string | null;
  createdBy: string | AuthUser;
  lastEditedBy: string | AuthUser;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 公告发布后出现在公开公告列表及详情页。先保存草稿并核对正文，再使用现有发布动作公开；Unpublish 会从公开列表移除。点击列表标题进入编辑。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: string;
  /**
   * 显示在公开公告列表和公告详情页顶部。
   */
  title: string;
  /**
   * 可公开，供公告列表快速了解内容；不代替正文。
   */
  summary?: string | null;
  slug: string;
  /**
   * 公告详情页公开展示的主要内容。
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt?: string | null;
  createdBy: string | AuthUser;
  lastEditedBy: string | AuthUser;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 固定页面会显示在公开 Web 对应位置。先保存草稿并核对正文，再使用现有发布动作公开；首页首次发布后不能下线。点击列表标题进入编辑。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "association-pages".
 */
export interface AssociationPage {
  id: string;
  /**
   * 固定页面身份创建后不可修改。
   */
  pageKey: 'home' | 'about' | 'contact';
  /**
   * 显示为公开页面的主标题，也用于后台列表识别。
   */
  title: string;
  /**
   * 可公开，用于搜索结果和页面元信息；不代替正文。
   */
  seoSummary?: string | null;
  /**
   * 仅首页显示的简短引导语。
   */
  lead?: string | null;
  /**
   * 公开页面的主要内容。
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * 只填写协会获准公开的公共联系方式，不填写成员私人联系方式。
   */
  contacts?:
    | {
        contactId: string;
        type: 'email' | 'phone' | 'qq' | 'wechat' | 'other';
        label?: string | null;
        value?: string | null;
        note?: string | null;
        isPublic?: boolean | null;
        showOnHome?: boolean | null;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  createdBy: string | AuthUser;
  lastEditedBy: string | AuthUser;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 单图协会作品。上传只接受 JPEG、静态 PNG/WebP，原件不保留；公开署名优先笔名，否则回退作者显示名。保存草稿不会改变当前公开版本；发布前须确认展示权利与人物授权。下线会关闭匿名入口，但无法召回访客已下载的副本。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-works".
 */
export interface GalleryWork {
  id: string;
  title: string;
  summary?: string | null;
  slug: string;
  media: string | MediaAsset;
  altText: string;
  /**
   * 默认当前操作者。只有账号管理员可经画廊作者候选入口选择其他账号。
   */
  author: string | AuthUser;
  penName?: string | null;
  publicAuthorName?: string | null;
  displayRightsConfirmed: boolean;
  recognizablePeople?: ('none' | 'consentConfirmed') | null;
  publishedAt?: string | null;
  createdBy: string | AuthUser;
  lastEditedBy: string | AuthUser;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 仅保存已完成安全处理的站点图片。原始上传不会保留；资产不可替换或删除。对象 key 不公开。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-assets".
 */
export interface MediaAsset {
  id: string;
  objectPrefix: string;
  sha256: string;
  mimeType: string;
  width: number;
  height: number;
  byteSize: number;
  display: {
    objectKey: string;
    sha256: string;
    mimeType: string;
    width: number;
    height: number;
    byteSize: number;
  };
  detail: {
    objectKey: string;
    sha256: string;
    mimeType: string;
    width: number;
    height: number;
    byteSize: number;
  };
  list: {
    objectKey: string;
    sha256: string;
    mimeType: string;
    width: number;
    height: number;
    byteSize: number;
  };
  thumbnail: {
    objectKey: string;
    sha256: string;
    mimeType: string;
    width: number;
    height: number;
    byteSize: number;
  };
  createdBy: string | AuthUser;
  updatedAt: string;
  createdAt: string;
}
/**
 * 新闻发布后出现在公开新闻列表及详情页。保存草稿或新版草稿不会改变当前公开版本；公开新版本使用现有发布动作，下线使用 Unpublish。点击列表标题进入编辑。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  /**
   * 显示在公开新闻列表和新闻详情页顶部。
   */
  title: string;
  /**
   * 可公开，供新闻列表快速了解内容；只填写单行纯文本，不代替正文。
   */
  summary?: string | null;
  /**
   * 创建时由服务端生成，后续不可修改。
   */
  slug: string;
  /**
   * 新闻详情页公开展示的主要内容。
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt?: string | null;
  createdBy: string | AuthUser;
  lastEditedBy: string | AuthUser;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 历史招新届次，仅供演示和工程调试；不得录入真实个人资料。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment-cycles".
 */
export interface RecruitmentCycle {
  id: string;
  code: string;
  name: string;
  status: 'draft' | 'open' | 'closed' | 'archived';
  opensAt?: string | null;
  closesAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 历史动态表单定义，仅供演示和工程调试；不得录入真实个人资料。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-definitions".
 */
export interface FormDefinition {
  id: string;
  recruitmentCycle: string | RecruitmentCycle;
  name: string;
  /**
   * 仅草稿可编辑；发布会创建不可变的表单版本快照。
   */
  draftSchema:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-versions".
 */
export interface FormVersion {
  id: string;
  formDefinition: string | FormDefinition;
  recruitmentCycle: string | RecruitmentCycle;
  version: number;
  status: 'published' | 'retired';
  schema:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  schemaHash: string;
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * 历史招新申请，仅供演示和工程调试；不是当前会员账号申领入口，不得录入真实个人资料。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-applications".
 */
export interface MembershipApplication {
  id: string;
  recruitmentCycle: string | RecruitmentCycle;
  formVersion: string | FormVersion;
  status: 'pending' | 'approved' | 'rejected';
  answers:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  idempotencyKey: string;
  recordVersion: number;
  submittedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * 正式会员档案；账号创建与会员认领请使用受控业务页面。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: string;
  studentNumber?: string | null;
  name: string;
  membershipIdentity?: ('member' | 'staff' | 'cadre') | null;
  contacts?:
    | {
        type: 'phone' | 'wechat' | 'qq' | 'other';
        label?: string | null;
        value: string;
        isPrimary: boolean;
        id?: string | null;
      }[]
    | null;
  major?: string | null;
  source?: ('offlineInterview' | 'manualVerification') | null;
  sourceApplication?: (string | null) | MembershipApplication;
  authUser?: (string | null) | AuthUser;
  recordVersion: number;
  confirmedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-actions".
 */
export interface ReviewAction {
  id: string;
  application: string | MembershipApplication;
  reviewer: string | AuthUser;
  action: 'approve' | 'reject';
  comment?: string | null;
  actedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-claims".
 */
export interface AccountClaim {
  id: string;
  member: string | Member;
  authUser: string | AuthUser;
  status: 'pendingReview' | 'approved' | 'rejected';
  applicantIdentity: 'member' | 'staff' | 'cadre';
  contacts?:
    | {
        type: 'phone' | 'wechat' | 'qq' | 'other';
        label?: string | null;
        value: string;
        isPrimary: boolean;
        id?: string | null;
      }[]
    | null;
  major?: string | null;
  idempotencyKey: string;
  requestFingerprint: string;
  submittedAuthUserVersion: number;
  authorizationSummary:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  submittedAt: string;
  reviewedAt?: string | null;
  reviewedBy?: (string | null) | AuthUser;
  publicMessage?: string | null;
  publicMessageUpdatedAt?: string | null;
  publicMessageUpdatedBy?: (string | null) | AuthUser;
  statusAccessVersion: number;
  statusAccessIssuedAt?: string | null;
  convertedAt?: string | null;
  convertedAccountVersion?: number | null;
  conversionWithdrawnAt?: string | null;
  conversionWithdrawnBy?: (string | null) | AuthUser;
  rejectionReason?:
    | (
        | 'identityMismatch'
        | 'duplicateOrExistingAccount'
        | 'insufficientEvidence'
        | 'policyOrEligibility'
        | 'applicantRequest'
        | 'other'
      )
    | null;
  requestId: string;
  recordVersion: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-intake-applications".
 */
export interface MemberIntakeApplication {
  id: string;
  status: 'pendingReview' | 'approved' | 'rejected';
  name?: string | null;
  studentNumber?: string | null;
  applicantIdentity: 'member' | 'staff' | 'cadre';
  contacts?:
    | {
        type: 'phone' | 'wechat' | 'qq' | 'other';
        label?: string | null;
        value: string;
        isPrimary: boolean;
        id?: string | null;
      }[]
    | null;
  major?: string | null;
  privacyPurposeConfirmed?: boolean | null;
  member?: (string | null) | Member;
  idempotencyKey: string;
  requestFingerprint: string;
  submittedAt: string;
  reviewedAt?: string | null;
  reviewedBy?: (string | null) | AuthUser;
  publicMessage?: string | null;
  publicMessageUpdatedAt?: string | null;
  publicMessageUpdatedBy?: (string | null) | AuthUser;
  statusAccessVersion: number;
  statusAccessIssuedAt?: string | null;
  rejectionReason?:
    | (
        | 'identityMismatch'
        | 'duplicateOrExistingAccount'
        | 'insufficientEvidence'
        | 'policyOrEligibility'
        | 'applicantRequest'
        | 'other'
      )
    | null;
  requestId: string;
  recordVersion: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * 只读的关键业务操作审计记录。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: string;
  actor?: (string | null) | AuthUser;
  action: string;
  targetType: string;
  targetId: string;
  result: string;
  requestId: string;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  occurredAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permission-overrides".
 */
export interface PermissionOverride {
  id: string;
  user: string | AuthUser;
  permission:
    | 'recruitment.application.read'
    | 'recruitment.application.review'
    | 'recruitment.form.manage'
    | 'content.create'
    | 'content.edit'
    | 'content.directPublish'
    | 'audit.read'
    | 'accounts.manage';
  effect: 'allow' | 'deny';
  scopeType: 'global' | 'recruitmentCycle';
  recruitmentCycle?: (string | null) | RecruitmentCycle;
  expiresAt?: string | null;
  reason?: string | null;
  grantedBy?: (string | null) | AuthUser;
  grantedAt?: string | null;
  revokedBy?: (string | null) | AuthUser;
  revokedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'auth-users';
        value: string | AuthUser;
      } | null)
    | ({
        relationTo: 'demo-pages';
        value: string | DemoPage;
      } | null)
    | ({
        relationTo: 'activities';
        value: string | Activity;
      } | null)
    | ({
        relationTo: 'announcements';
        value: string | Announcement;
      } | null)
    | ({
        relationTo: 'association-pages';
        value: string | AssociationPage;
      } | null)
    | ({
        relationTo: 'gallery-works';
        value: string | GalleryWork;
      } | null)
    | ({
        relationTo: 'news';
        value: string | News;
      } | null)
    | ({
        relationTo: 'media-assets';
        value: string | MediaAsset;
      } | null)
    | ({
        relationTo: 'recruitment-cycles';
        value: string | RecruitmentCycle;
      } | null)
    | ({
        relationTo: 'form-definitions';
        value: string | FormDefinition;
      } | null)
    | ({
        relationTo: 'form-versions';
        value: string | FormVersion;
      } | null)
    | ({
        relationTo: 'membership-applications';
        value: string | MembershipApplication;
      } | null)
    | ({
        relationTo: 'members';
        value: string | Member;
      } | null)
    | ({
        relationTo: 'review-actions';
        value: string | ReviewAction;
      } | null)
    | ({
        relationTo: 'account-claims';
        value: string | AccountClaim;
      } | null)
    | ({
        relationTo: 'member-intake-applications';
        value: string | MemberIntakeApplication;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: string | AuditEvent;
      } | null)
    | ({
        relationTo: 'permission-overrides';
        value: string | PermissionOverride;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'auth-users';
    value: string | AuthUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'auth-users';
    value: string | AuthUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-users_select".
 */
export interface AuthUsersSelect<T extends boolean = true> {
  displayName?: T;
  accountType?: T;
  studentNumber?: T;
  status?: T;
  role?: T;
  defaultRoleExpiresAt?: T;
  temporaryCredentialExpiresAt?: T;
  recordVersion?: T;
  accessExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demo-pages_select".
 */
export interface DemoPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  activityType?: T;
  title?: T;
  summary?: T;
  slug?: T;
  location?: T;
  startsAt?: T;
  endsAt?: T;
  scheduleText?: T;
  isCancelled?: T;
  cancellationNote?: T;
  body?: T;
  publishedAt?: T;
  historySortAt?: T;
  createdBy?: T;
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  slug?: T;
  body?: T;
  publishedAt?: T;
  createdBy?: T;
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "association-pages_select".
 */
export interface AssociationPagesSelect<T extends boolean = true> {
  pageKey?: T;
  title?: T;
  seoSummary?: T;
  lead?: T;
  body?: T;
  contacts?:
    | T
    | {
        contactId?: T;
        type?: T;
        label?: T;
        value?: T;
        note?: T;
        isPublic?: T;
        showOnHome?: T;
        id?: T;
      };
  publishedAt?: T;
  createdBy?: T;
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-works_select".
 */
export interface GalleryWorksSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  slug?: T;
  media?: T;
  altText?: T;
  author?: T;
  penName?: T;
  publicAuthorName?: T;
  displayRightsConfirmed?: T;
  recognizablePeople?: T;
  publishedAt?: T;
  createdBy?: T;
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  slug?: T;
  body?: T;
  publishedAt?: T;
  createdBy?: T;
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-assets_select".
 */
export interface MediaAssetsSelect<T extends boolean = true> {
  objectPrefix?: T;
  sha256?: T;
  mimeType?: T;
  width?: T;
  height?: T;
  byteSize?: T;
  display?:
    | T
    | {
        objectKey?: T;
        sha256?: T;
        mimeType?: T;
        width?: T;
        height?: T;
        byteSize?: T;
      };
  detail?:
    | T
    | {
        objectKey?: T;
        sha256?: T;
        mimeType?: T;
        width?: T;
        height?: T;
        byteSize?: T;
      };
  list?:
    | T
    | {
        objectKey?: T;
        sha256?: T;
        mimeType?: T;
        width?: T;
        height?: T;
        byteSize?: T;
      };
  thumbnail?:
    | T
    | {
        objectKey?: T;
        sha256?: T;
        mimeType?: T;
        width?: T;
        height?: T;
        byteSize?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment-cycles_select".
 */
export interface RecruitmentCyclesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  status?: T;
  opensAt?: T;
  closesAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-definitions_select".
 */
export interface FormDefinitionsSelect<T extends boolean = true> {
  recruitmentCycle?: T;
  name?: T;
  draftSchema?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-versions_select".
 */
export interface FormVersionsSelect<T extends boolean = true> {
  formDefinition?: T;
  recruitmentCycle?: T;
  version?: T;
  status?: T;
  schema?: T;
  schemaHash?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-applications_select".
 */
export interface MembershipApplicationsSelect<T extends boolean = true> {
  recruitmentCycle?: T;
  formVersion?: T;
  status?: T;
  answers?: T;
  idempotencyKey?: T;
  recordVersion?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  studentNumber?: T;
  name?: T;
  membershipIdentity?: T;
  contacts?:
    | T
    | {
        type?: T;
        label?: T;
        value?: T;
        isPrimary?: T;
        id?: T;
      };
  major?: T;
  source?: T;
  sourceApplication?: T;
  authUser?: T;
  recordVersion?: T;
  confirmedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-actions_select".
 */
export interface ReviewActionsSelect<T extends boolean = true> {
  application?: T;
  reviewer?: T;
  action?: T;
  comment?: T;
  actedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-claims_select".
 */
export interface AccountClaimsSelect<T extends boolean = true> {
  member?: T;
  authUser?: T;
  status?: T;
  applicantIdentity?: T;
  contacts?:
    | T
    | {
        type?: T;
        label?: T;
        value?: T;
        isPrimary?: T;
        id?: T;
      };
  major?: T;
  idempotencyKey?: T;
  requestFingerprint?: T;
  submittedAuthUserVersion?: T;
  authorizationSummary?: T;
  submittedAt?: T;
  reviewedAt?: T;
  reviewedBy?: T;
  publicMessage?: T;
  publicMessageUpdatedAt?: T;
  publicMessageUpdatedBy?: T;
  statusAccessVersion?: T;
  statusAccessIssuedAt?: T;
  convertedAt?: T;
  convertedAccountVersion?: T;
  conversionWithdrawnAt?: T;
  conversionWithdrawnBy?: T;
  rejectionReason?: T;
  requestId?: T;
  recordVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-intake-applications_select".
 */
export interface MemberIntakeApplicationsSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  studentNumber?: T;
  applicantIdentity?: T;
  contacts?:
    | T
    | {
        type?: T;
        label?: T;
        value?: T;
        isPrimary?: T;
        id?: T;
      };
  major?: T;
  privacyPurposeConfirmed?: T;
  member?: T;
  idempotencyKey?: T;
  requestFingerprint?: T;
  submittedAt?: T;
  reviewedAt?: T;
  reviewedBy?: T;
  publicMessage?: T;
  publicMessageUpdatedAt?: T;
  publicMessageUpdatedBy?: T;
  statusAccessVersion?: T;
  statusAccessIssuedAt?: T;
  rejectionReason?: T;
  requestId?: T;
  recordVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  targetType?: T;
  targetId?: T;
  result?: T;
  requestId?: T;
  metadata?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permission-overrides_select".
 */
export interface PermissionOverridesSelect<T extends boolean = true> {
  user?: T;
  permission?: T;
  effect?: T;
  scopeType?: T;
  recruitmentCycle?: T;
  expiresAt?: T;
  reason?: T;
  grantedBy?: T;
  grantedAt?: T;
  revokedBy?: T;
  revokedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}